image:
  repository: neo9sas/ingress-access-operator
  pullPolicy: Always
  tag: latest

pod:
  env:
    values:
    - name: EXTENSION_UPDATE_ISTIO_INGRESS_SIDECAR_ENABLED
      value: false
    - name: EXTENSION_EXPOSER_ENABLED
      value: false
    - name: EXTENSION_DEFAULT_FILTERING_ENABLED
      value: false
    - name: AWS_REGION
      value: eu-central-1

serviceAccount:
  create: true
  name: "ingress-access-operator-sa"

healthCheck:
  path: "/actuator/health"

service:
  port: 8081

clusterrole:
  enabled: true
  autoBindClusteRole: true
  rules:
    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get"]
    - apiGroups: ["ingress.neo9.io"]
      resources: ["visitorgroups"]
      verbs: ["get", "list", "watch", "update", "patch"]
    - apiGroups: ["ingress.neo9.io"]
      resources: ["visitorgroups/status"]
      verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["networking.istio.io"]
      resources: ["sidecars"]
      verbs: ["get", "list", "watch", "update", "patch", "create"]
