server:
  port: 8081

spring:
  main:
    banner-mode: "off"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.neo9.ingress.access: DEBUG
    io.javaoperatorsdk.operator: DEBUG

javaoperatorsdk:
  controllers:
    visitorgroupcontroller:
      retry:
        maxAttempts: 3

extension:

  updateIstioIngressSidecar:
    enabled: false
    ingressNamespace: nginx-istio-ingress
    additionalEgressRulesEntries:
      - "istio-system"

  exposer:
    enabled: false
    domain: neokube.pro
    hostnameTemplate: "{{name}}.{{namespace}}.{{domain}}"
    tlsEnabledDetectionAnnotation:
      - cert-manager.io/issuer
      - cert-manager.io/cluster-issuer

  defaultFiltering:
    enabled: false
    categories:
      - default

  awsConfig:
    enabled: false
    #wafArn: ""
